name: shellcheck

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck
    - name: shellcheck
      run: |
        shellcheck bids-basher
